languageCode = "de"
languageName = "Deutsch"
displayName = "DE"
isoCode = "de"
weight = 2
rtl = false

copyright = "" # TODO CC BY 

dateFormat = "2 January 2006"

[author]
  name = "Dr. Jan Renz"
  image = "img/jan_avatar.jpg"
  headline = "Digitalisierung und Infrastrukturen für und in der Bildung"
  bio = "" # about me
  links = [
    { mastodon = "https://bildung.social/@janprenz" },
    { linkedin = "https://www.linkedin.com/in/jan-renz-7265936b/" },
  ]