languageCode = "en-us"
languageName = "English"
displayName = "🇬🇧"
isoCode = "en"
weight = 1
rtl = false

copyright = "" # TODO CC BY 

dateFormat = "2 January 2006"

[author]
  name = "Dr. Jan Renz"
  image = "/img/jan_avatar.jpg"
  headline = "Digitalisation and infrastructures for education"
  bio = "" # about me
  links = [
    { mastodon = "https://bildung.social/@janprenz" },
    { linkedin = "https://www.linkedin.com/in/jan-renz-7265936b/" },
  ]