baseURL = 'https://janrenz.de'
languageCode = 'de'
title = 'Jan Renz'
defaultContentLanguage = 'de'
[languages]
  [languages.de]
    title = 'Mein persönlicher Blog'
  [languages.en]
    title = 'My personal blog'
